### ISSUE TITLE
throwing exception  KeyError: 'c' sometime

### ISSUE THREAD

**Issue by ghost** [sagarsuman00/market_monitor#4]
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 839, in callit
    func(*args)
  File "/home/sagar/personal/market_monitor/market_monitor.py", line 221, in update_labels
    widget_item.update_label()
  File "/home/sagar/personal/market_monitor/market_monitor.py", line 122, in update_label
    t_value = self.market.get_current_value()
  File "/home/sagar/personal/market_monitor/market_monitor.py", line 53, in get_current_value
    return self.get_response('1',Time)
  File "/home/sagar/personal/market_monitor/market_monitor.py", line 78, in get_response
    return df.at[0, 'c']
  File "/home/sagar/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 2575, in __getitem__
    return super().__getitem__(key)
  File "/home/sagar/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 2527, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/home/sagar/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 4202, in _get_value
    series = self._get_item_cache(col)
  File "/home/sagar/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 4626, in _get_item_cache
    loc = self.columns.get_loc(item)
  File "/home/sagar/.local/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'c'

**Comment by ghost** [comment]
Root cause found. Sometimes API endpoint doesn't send data. Resolved this issue.
